name: Release Builds

on: push

env:
  LLVM_VERSION: "17.0.4"
  QT_VERSION: "v6.6.0"
  ZLIB_VERSION: "v1.3"
  LIBSBML_VERSION: "development"
  LIBEXPAT_VERSION: "R_2_5_0"
  SYMENGINE_VERSION: "v0.11.1"
  GMP_VERSION: "6.3.0"
  MPFR_VERSION: "4.2.1"
  SPDLOG_VERSION: "v1.12.0"
  LIBTIFF_VERSION: "v4.6.0"
  FMT_VERSION: "10.1.1"
  TBB_VERSION: "fix_1145_missing_threads_dependency_static_build"
  DPL_VERSION: "oneDPL-2022.2.0-rc1"
  OPENCV_VERSION: "4.8.1"
  CATCH2_VERSION: "v3.4.0"
  BENCHMARK_VERSION: "v1.8.3"
  CGAL_VERSION: "v5.6"
  BOOST_VERSION: "1.83.0"
  BOOST_VERSION_: "1_83_0"
  QCUSTOMPLOT_VERSION: "2.1.1"
  CEREAL_VERSION: "v1.3.2"
  PAGMO_VERSION: "v2.19.0"
  BZIP2_VERSION: "1.0.8"
  ZIPPER_VERSION: "master"
  COMBINE_VERSION: "master"
  FUNCTION2_VERSION: "4.2.4"
  DUNE_COPASI_VERSION: "ci_fixes_for_dune_copasi_2_xcode"

jobs:
  macos-arm64:
    name: MacOS Arm64
    runs-on: macos-arm64-ssc
    env:
      INSTALL_PREFIX: "/opt/smelibs"
      SUDOCMD: "sudo -E"
      MACOSX_DEPLOYMENT_TARGET: "11"
      TARGET_TRIPLE: "aarch64-apple-darwin20.1.0"
      BOOST_INSTALL_PREFIX: "/opt/smelibs"
      BOOST_BOOTSTRAP_OPTIONS: ""
      BOOST_B2_OPTIONS: 'cxxflags="-mmacosx-version-min=11" linkflags="-mmacosx-version-min=11"'
      PYTHON_EXE: "/opt/homebrew/bin/python3.12"
      OS_TARGET: "osx-arm64"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3"
      - run: ./llvm.sh
      - run: ./qt.sh
      - run: ./common.sh
      - run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./artefacts/*
