name: Release Builds

on: push

env:
  LLVM_VERSION: "17.0.6"
  QT_VERSION: "v6.6.1"
  ZLIB_VERSION: "v1.3"
  LIBSBML_VERSION: "development"
  LIBEXPAT_VERSION: "R_2_5_0"
  SYMENGINE_VERSION: "master"
  GMP_VERSION: "6.3.0"
  MPFR_VERSION: "4.2.1"
  SPDLOG_VERSION: "v1.13.0"
  LIBTIFF_VERSION: "v4.6.0"
  FMT_VERSION: "10.2.1"
  TBB_VERSION: "fix_1145_missing_threads_dependency_static_build"
  DPL_VERSION: "oneDPL-2022.2.0-rc1"
  OPENCV_VERSION: "4.9.0"
  CATCH2_VERSION: "v3.5.1"
  BENCHMARK_VERSION: "v1.8.3"
  CGAL_VERSION: "v5.6"
  BOOST_VERSION: "1.84.0"
  BOOST_VERSION_: "1_84_0"
  QCUSTOMPLOT_VERSION: "2.1.1"
  CEREAL_VERSION: "v1.3.2"
  PAGMO_VERSION: "v2.19.0"
  BZIP2_VERSION: "1.0.8"
  ZIPPER_VERSION: "master"
  COMBINE_VERSION: "master"
  FUNCTION2_VERSION: "4.2.4"
  VTK_VERSION: "v9.3.0"
  SCOTCH_VERSION: "v7.0.4"
  DUNE_COPASI_VERSION: "master"

jobs:
  macos-arm64:
    name: MacOS Arm64
    runs-on: macos-arm64-ssc
    env:
      INSTALL_PREFIX: "/opt/smelibs"
      SUDOCMD: "sudo -E"
      MACOSX_DEPLOYMENT_TARGET: "11"
      TARGET_TRIPLE: "aarch64-apple-darwin20.1.0"
      BOOST_INSTALL_PREFIX: "/opt/smelibs"
      BOOST_BOOTSTRAP_OPTIONS: ""
      BOOST_B2_OPTIONS: 'cxxflags="-mmacosx-version-min=11" linkflags="-mmacosx-version-min=11"'
      PYTHON_EXE: "/opt/homebrew/bin/python3.12"
      OS_TARGET: "osx-arm64"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3"
      - run: ./llvm.sh
      - run: ./qt.sh
      - run: ./common.sh
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-arm64
          path: ./artefacts/*
  release:
    name: Upload Binaries to GitHub Release
    needs: [macos-arm64]
    runs-on: ubuntu-latest
    # upload binaries to github release if commit is tagged
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          merge-multiple: true
          path: binaries
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
